### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'clinvar'

### ISSUE THREAD

**Issue by mgalardini** [allydunham/sequence_unet#3]
Hi there!

I wanted to give it a go with one of the command line scripts and it seems to me that perhaps the script needs to be edited:

```
$ sequence_unet --fasta acrB.faa freq_classifier
[a bunch ow TF-related warnings]
2023-09-04 15:31:57.768653: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-04 15:31:57.798557: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-04 15:31:58.386480: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/fast-storage/marco/sequence_unet/venv/bin/sequence_unet", line 8, in <module>
    sys.exit(main())
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/sequence_unet/scripts/make_preds.py", line 31, in main
    args = parse_args()
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/sequence_unet/scripts/make_preds.py", line 95, in parse_args
    if args.clinvar and args.tsv is None:
AttributeError: 'Namespace' object has no attribute 'clinvar'
```

However, when I do `sequence_unet -h` I don't see any `--clinvar` argument. After commenting out [5 lines starting here](https://github.com/allydunham/sequence_unet/blob/master/sequence_unet/scripts/make_preds.py#L95) I don't get the same error anymore.

Hope this helps, and thanks for putting this piece of software together!

**Comment by allydunham** [comment]
Hi! Glad you're using it and hopefully it's helpful.

Thanks for noticing this, I somehow hadn't updated the predictions script from an old version I was using internally that had various filtering options (--clinvar/--tsv) that got removed from the final package for simplicity.

I've pushed a commit that removes the leftover references and tidys up the help text to correctly describe it. I think this should work now - I'm able to make predictions against fasta files at least. There might still be some things I've missed though, let me know if you run in to anything else!

**Comment by mgalardini** [comment]
Thanks for the quick fix! I am getting a new error now which may be related to the way the models are saved after download:

```$ python sequence_unet/scripts/make_preds.py --fasta acrB.faa -d -m downloaded_models freq_classifier
[TF warnings]
Downloading freq_classifier: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512M/512M [01:04<00:00, 7.88MB/s]
Traceback (most recent call last):
  File "sequence_unet/scripts/make_preds.py", line 82, in <module>
    main()
  File "sequence_unet/scripts/make_preds.py", line 20, in main
    model = load_trained_model(args.model, args.model_dir, download=args.download)
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/sequence_unet/models.py", line 245, in load_trained_model
    return models.load_model(path, custom_objects=CUSTOM_OBJECTS)
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/keras/src/saving/saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/fast-storage/marco/sequence_unet/venv/lib/python3.8/site-packages/keras/src/saving/legacy/save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at downloaded_models/freq_classifier.tf
```

The `downloaded_models` directory exists...

**Comment by mgalardini** [comment]
whoops, forgot to add the command line I used: `$ python sequence_unet/scripts/make_preds.py --fasta acrB.faa -d -m downloaded_models freq_classifier`

**Comment by mgalardini** [comment]
To follow up, I found that if I ask the script to download to the working directory it works: `$ python sequence_unet/scripts/make_preds.py --fasta acrB.faa -d -m downloaded_models freq_classifier`, so I think the problem is with the function that unpacks the downloaded tar file

**Comment by allydunham** [comment]
The tar unpacking is done with a shutil function and it looks like I forgot the extract_dir argument. I'll have a closer look and put a fix up when I get back next week, but I imagine adding that argument in will fix it if you want to try before then.

I thought I'd downloaded to folders before, but when I tested I think I used CWD too so must have overlooked this.

As an aside once you install with pip you should be able to call that script with `sequence_unet --fasta seqs.fa ...`. That won't change any behaviour I don't think though.

**Comment by allydunham** [comment]
I've updated this now and that has done the trick as far as I can tell.

Let me know if you have any other bugs or suggestions!
